interface Country {
  countryName: string;
  value: string;
  averageLife: number;
}

export const countries: Country[] = [
  { countryName: "Afghanistan", value: "afghanistan", averageLife: 64.8 },
  { countryName: "Albania", value: "albania", averageLife: 78.7 },
  { countryName: "Algeria", value: "algeria", averageLife: 76.5 },
  { countryName: "Andorra", value: "andorra", averageLife: 84.8 },
  { countryName: "Angola", value: "angola", averageLife: 61.2 },
  { countryName: "Antigua and Barbuda", value: "antigua_and_barbuda", averageLife: 76.5 },
  { countryName: "Argentina", value: "argentina", averageLife: 76.9 },
  { countryName: "Armenia", value: "armenia", averageLife: 74.8 },
  { countryName: "Australia", value: "australia", averageLife: 82.9 },
  { countryName: "Austria", value: "austria", averageLife: 81.5 },
  { countryName: "Azerbaijan", value: "azerbaijan", averageLife: 73.0 },
  { countryName: "Bahamas", value: "bahamas", averageLife: 72.3 },
  { countryName: "Bahrain", value: "bahrain", averageLife: 78.4 },
  { countryName: "Bangladesh", value: "bangladesh", averageLife: 73.8 },
  { countryName: "Barbados", value: "barbados", averageLife: 79.1 },
  { countryName: "Belarus", value: "belarus", averageLife: 74.2 },
  { countryName: "Belgium", value: "belgium", averageLife: 81.7 },
  { countryName: "Belize", value: "belize", averageLife: 74.0 },
  { countryName: "Benin", value: "benin", averageLife: 61.4 },
  { countryName: "Bhutan", value: "bhutan", averageLife: 71.8 },
  { countryName: "Bolivia", value: "bolivia", averageLife: 72.7 },
  { countryName: "Bosnia and Herzegovina", value: "bosnia_and_herzegovina", averageLife: 77.4 },
  { countryName: "Botswana", value: "botswana", averageLife: 69.0 },
  { countryName: "Brazil", value: "brazil", averageLife: 75.6 },
  { countryName: "Brunei", value: "brunei", averageLife: 77.8 },
  { countryName: "Bulgaria", value: "bulgaria", averageLife: 74.4 },
  { countryName: "Burkina Faso", value: "burkina_faso", averageLife: 61.2 },
  { countryName: "Burundi", value: "burundi", averageLife: 61.4 },
  { countryName: "Cabo Verde", value: "cabo_verde", averageLife: 73.2 },
  { countryName: "Cambodia", value: "cambodia", averageLife: 70.9 },
  { countryName: "Cameroon", value: "cameroon", averageLife: 60.6 },
  { countryName: "Canada", value: "canada", averageLife: 82.3 },
  { countryName: "Central African Republic", value: "central_african_republic", averageLife: 54.0 },
  { countryName: "Chad", value: "chad", averageLife: 54.0 },
  { countryName: "Chile", value: "chile", averageLife: 80.3 },
  { countryName: "China", value: "china", averageLife: 77.4 },
  { countryName: "Colombia", value: "colombia", averageLife: 77.1 },
  { countryName: "Comoros", value: "comoros", averageLife: 65.2 },
  { countryName: "Congo (Congo-Brazzaville)", value: "congo", averageLife: 64.6 },
  { countryName: "Congo (Democratic Republic)", value: "congo_democratic_republic", averageLife: 60.7 },
  { countryName: "Costa Rica", value: "costa_rica", averageLife: 80.0 },
  { countryName: "Croatia", value: "croatia", averageLife: 78.3 },
  { countryName: "Cuba", value: "cuba", averageLife: 78.8 },
  { countryName: "Cyprus", value: "cyprus", averageLife: 81.4 },
  { countryName: "Czech Republic", value: "czech_republic", averageLife: 79.3 },
  { countryName: "Denmark", value: "denmark", averageLife: 81.3 },
  { countryName: "Djibouti", value: "djibouti", averageLife: 67.1 },
  { countryName: "Dominica", value: "dominica", averageLife: 77.4 },
  { countryName: "Dominican Republic", value: "dominican_republic", averageLife: 74.2 },
  { countryName: "Ecuador", value: "ecuador", averageLife: 77.3 },
  { countryName: "Egypt", value: "egypt", averageLife: 72.5 },
  { countryName: "El Salvador", value: "el_salvador", averageLife: 74.7 },
  { countryName: "Equatorial Guinea", value: "equatorial_guinea", averageLife: 58.0 },
  { countryName: "Eritrea", value: "eritrea", averageLife: 66.9 },
  { countryName: "Estonia", value: "estonia", averageLife: 78.7 },
  { countryName: "Eswatini", value: "eswatini", averageLife: 60.3 },
  { countryName: "Ethiopia", value: "ethiopia", averageLife: 67.0 },
  { countryName: "Fiji", value: "fiji", averageLife: 67.4 },
  { countryName: "Finland", value: "finland", averageLife: 81.8 },
  { countryName: "France", value: "france", averageLife: 82.4 },
  { countryName: "Gabon", value: "gabon", averageLife: 66.0 },
  { countryName: "Gambia", value: "gambia", averageLife: 62.1 },
  { countryName: "Georgia", value: "georgia", averageLife: 73.4 },
  { countryName: "Germany", value: "germany", averageLife: 81.0 },
  { countryName: "Ghana", value: "ghana", averageLife: 64.1 },
  { countryName: "Greece", value: "greece", averageLife: 82.3 },
  { countryName: "Grenada", value: "grenada", averageLife: 73.0 },
  { countryName: "Guatemala", value: "guatemala", averageLife: 73.7 },
  { countryName: "Guinea", value: "guinea", averageLife: 62.5 },
  { countryName: "Guinea-Bissau", value: "guinea_bissau", averageLife: 59.3 },
  { countryName: "Guyana", value: "guyana", averageLife: 68.4 },
  { countryName: "Haiti", value: "haiti", averageLife: 64.0 },
  { countryName: "Honduras", value: "honduras", averageLife: 75.1 },
  { countryName: "Hungary", value: "hungary", averageLife: 76.7 },
  { countryName: "Iceland", value: "iceland", averageLife: 82.9 },
  { countryName: "India", value: "india", averageLife: 70.8 },
  { countryName: "Indonesia", value: "indonesia", averageLife: 71.9 },
  { countryName: "Iran", value: "iran", averageLife: 76.5 },
  { countryName: "Iraq", value: "iraq", averageLife: 70.4 },
  { countryName: "Ireland", value: "ireland", averageLife: 82.3 },
  { countryName: "Israel", value: "israel", averageLife: 83.3 },
  { countryName: "Italy", value: "italy", averageLife: 83.6 },
  { countryName: "Jamaica", value: "jamaica", averageLife: 74.5 },
  { countryName: "Japan", value: "japan", averageLife: 84.5 },
  { countryName: "Jordan", value: "jordan", averageLife: 74.3 },
  { countryName: "Kazakhstan", value: "kazakhstan", averageLife: 73.1 },
  { countryName: "Kenya", value: "kenya", averageLife: 66.7 },
  { countryName: "Kiribati", value: "kiribati", averageLife: 69.1 },
  { countryName: "Kuwait", value: "kuwait", averageLife: 75.9 },
  { countryName: "Kyrgyzstan", value: "kyrgyzstan", averageLife: 71.6 },
  { countryName: "Laos", value: "laos", averageLife: 68.4 },
  { countryName: "Latvia", value: "latvia", averageLife: 75.1 },
  { countryName: "Lebanon", value: "lebanon", averageLife: 79.4 },
  { countryName: "Lesotho", value: "lesotho", averageLife: 55.8 },
  { countryName: "Liberia", value: "liberia", averageLife: 64.1 },
  { countryName: "Libya", value: "libya", averageLife: 72.7 },
  { countryName: "Liechtenstein", value: "liechtenstein", averageLife: 82.1 },
  { countryName: "Lithuania", value: "lithuania", averageLife: 75.9 },
  { countryName: "Luxembourg", value: "luxembourg", averageLife: 82.5 },
  { countryName: "Madagascar", value: "madagascar", averageLife: 67.5 },
  { countryName: "Malawi", value: "malawi", averageLife: 64.3 },
  { countryName: "Malaysia", value: "malaysia", averageLife: 75.6 },
  { countryName: "Maldives", value: "maldives", averageLife: 78.9 },
  { countryName: "Mali", value: "mali", averageLife: 59.3 },
  { countryName: "Malta", value: "malta", averageLife: 82.6 },
  { countryName: "Marshall Islands", value: "marshall_islands", averageLife: 69.3 },
  { countryName: "Mauritania", value: "mauritania", averageLife: 64.4 },
  { countryName: "Mauritius", value: "mauritius", averageLife: 75.9 },
  { countryName: "Mexico", value: "mexico", averageLife: 75.2 },
  { countryName: "Micronesia", value: "micronesia", averageLife: 67.9 },
  { countryName: "Moldova", value: "moldova", averageLife: 71.8 },
  { countryName: "Monaco", value: "monaco", averageLife: 86.5 },
  { countryName: "Mongolia", value: "mongolia", averageLife: 70.1 },
  { countryName: "Montenegro", value: "montenegro", averageLife: 76.9 },
  { countryName: "Morocco", value: "morocco", averageLife: 77.4 },
  { countryName: "Mozambique", value: "mozambique", averageLife: 60.0 },
  { countryName: "Myanmar", value: "myanmar", averageLife: 67.9 },
  { countryName: "Namibia", value: "namibia", averageLife: 65.1 },
  { countryName: "Nauru", value: "nauru", averageLife: 67.2 },
  { countryName: "Nepal", value: "nepal", averageLife: 70.6 },
  { countryName: "Netherlands", value: "netherlands", averageLife: 81.9 },
  { countryName: "New Zealand", value: "new_zealand", averageLife: 82.4 },
  { countryName: "Nicaragua", value: "nicaragua", averageLife: 75.0 },
  { countryName: "Niger", value: "niger", averageLife: 62.4 },
  { countryName: "Nigeria", value: "nigeria", averageLife: 54.6 },
  { countryName: "North Korea", value: "north_korea", averageLife: 72.5 },
  { countryName: "North Macedonia", value: "north_macedonia", averageLife: 75.7 },
  { countryName: "Norway", value: "norway", averageLife: 82.9 },
  { countryName: "Oman", value: "oman", averageLife: 77.2 },
  { countryName: "Pakistan", value: "pakistan", averageLife: 67.3 },
  { countryName: "Palau", value: "palau", averageLife: 72.8 },
  { countryName: "Panama", value: "panama", averageLife: 78.6 },
  { countryName: "Papua New Guinea", value: "papua_new_guinea", averageLife: 64.2 },
  { countryName: "Paraguay", value: "paraguay", averageLife: 74.1 },
  { countryName: "Peru", value: "peru", averageLife: 77.3 },
  { countryName: "Philippines", value: "philippines", averageLife: 71.2 },
  { countryName: "Poland", value: "poland", averageLife: 78.5 },
  { countryName: "Portugal", value: "portugal", averageLife: 81.4 },
  { countryName: "Qatar", value: "qatar", averageLife: 80.2 },
  { countryName: "Romania", value: "romania", averageLife: 75.3 },
  { countryName: "Russia", value: "russia", averageLife: 72.6 },
  { countryName: "Rwanda", value: "rwanda", averageLife: 69.0 },
  { countryName: "Saint Kitts and Nevis", value: "saint_kitts_and_nevis", averageLife: 76.9 },
  { countryName: "Saint Lucia", value: "saint_lucia", averageLife: 77.4 },
  { countryName: "Saint Vincent and the Grenadines", value: "saint_vincent_and_the_grenadines", averageLife: 72.3 },
  { countryName: "Samoa", value: "samoa", averageLife: 73.7 },
  { countryName: "San Marino", value: "san_marino", averageLife: 83.1 },
  { countryName: "Sao Tome and Principe", value: "sao_tome_and_principe", averageLife: 68.7 },
  { countryName: "Saudi Arabia", value: "saudi_arabia", averageLife: 75.1 },
  { countryName: "Senegal", value: "senegal", averageLife: 68.8 },
  { countryName: "Serbia", value: "serbia", averageLife: 75.6 },
  { countryName: "Seychelles", value: "seychelles", averageLife: 73.0 },
  { countryName: "Sierra Leone", value: "sierra_leone", averageLife: 54.7 },
  { countryName: "Singapore", value: "singapore", averageLife: 83.7 },
  { countryName: "Slovakia", value: "slovakia", averageLife: 77.3 },
  { countryName: "Slovenia", value: "slovenia", averageLife: 81.5 },
  { countryName: "Solomon Islands", value: "solomon_islands", averageLife: 72.7 },
  { countryName: "Somalia", value: "somalia", averageLife: 56.6 },
  { countryName: "South Africa", value: "south_africa", averageLife: 64.1 },
  { countryName: "South Korea", value: "south_korea", averageLife: 83.3 },
  { countryName: "South Sudan", value: "south_sudan", averageLife: 57.3 },
  { countryName: "Spain", value: "spain", averageLife: 83.4 },
  { countryName: "Sri Lanka", value: "sri_lanka", averageLife: 76.8 },
  { countryName: "Sudan", value: "sudan", averageLife: 65.2 },
  { countryName: "Suriname", value: "suriname", averageLife: 72.0 },
  { countryName: "Sweden", value: "sweden", averageLife: 82.6 },
  { countryName: "Switzerland", value: "switzerland", averageLife: 83.4 },
  { countryName: "Syria", value: "syria", averageLife: 71.8 },
  { countryName: "Taiwan", value: "taiwan", averageLife: 81.0 },
  { countryName: "Tajikistan", value: "tajikistan", averageLife: 71.2 },
  { countryName: "Tanzania", value: "tanzania", averageLife: 66.4 },
  { countryName: "Thailand", value: "thailand", averageLife: 77.3 },
  { countryName: "Timor-Leste", value: "timor_leste", averageLife: 68.9 },
  { countryName: "Togo", value: "togo", averageLife: 61.4 },
  { countryName: "Tonga", value: "tonga", averageLife: 70.1 },
  { countryName: "Trinidad and Tobago", value: "trinidad_and_tobago", averageLife: 73.1 },
  { countryName: "Tunisia", value: "tunisia", averageLife: 76.9 },
  { countryName: "Turkey", value: "turkey", averageLife: 77.4 },
  { countryName: "Turkmenistan", value: "turkmenistan", averageLife: 68.9 },
  { countryName: "Tuvalu", value: "tuvalu", averageLife: 69.6 },
  { countryName: "Uganda", value: "uganda", averageLife: 63.2 },
  { countryName: "Ukraine", value: "ukraine", averageLife: 71.0 },
  { countryName: "United Arab Emirates", value: "united_arab_emirates", averageLife: 78.5 },
  { countryName: "United Kingdom", value: "united_kingdom", averageLife: 81.3 },
  { countryName: "United States", value: "united_states", averageLife: 78.5 },
  { countryName: "Uruguay", value: "uruguay", averageLife: 77.6 },
  { countryName: "Uzbekistan", value: "uzbekistan", averageLife: 71.0 },
  { countryName: "Vanuatu", value: "vanuatu", averageLife: 70.9 },
  { countryName: "Venezuela", value: "venezuela", averageLife: 72.1 },
  { countryName: "Vietnam", value: "vietnam", averageLife: 75.4 },
  { countryName: "Yemen", value: "yemen", averageLife: 66.5 },
  { countryName: "Zambia", value: "zambia", averageLife: 64.7 },
  { countryName: "Zimbabwe", value: "zimbabwe", averageLife: 61.2 }
]